Repository meyer-lab/tHMM, pull requests merged in 2019-06, with the labels that each got.

#115 New abstract
  manuscript/01_introduction.md
Labels: non-code

#119 Update 01_introduction.md
  manuscript/01_introduction.md
Labels: non-code

#125 Guide to code
  .gitignore
  Guide_to_tHMM.ipynb
  lineage/Breadth_Two_State_Lineage.py
  lineage/Depth_Two_State_Lineage.py
  lineage/figures/Fig_Gen.py
  lineage/figures/figure6.py
  lineage/figures/figure7.py
Labels: current

#124 Minor changes to introduction
  manuscript/01_introduction.md
  manuscript/references.bib
Labels: current, non-code
