Repository meyer-lab/tHMM, pull requests merged in 2020-03, with the labels that each got.

#234 Cleanup.
  lineage/DownwardRecursion.py
  lineage/UpwardRecursion.py
  lineage/Viterbi.py
Labels: speed

#235 Vector zetas
  lineage/BaumWelch.py
  lineage/Viterbi.py
  lineage/tHMM.py
Labels: speed

#236 State j
  lineage/BaumWelch.py
Labels: speed

#245 Get rid of one more loop.
  lineage/BaumWelch.py
  lineage/DownwardRecursion.py
Labels: speed

#243 Testing # of points increase (x10)
  .gitignore
  lineage/Analyze.py
  lineage/figures/figure3.py
  lineage/figures/figure4.py
  lineage/figures/figure6.py
Labels: speed

#254 Fig sizes and fix AIC figure
  lineage/UpwardRecursion.py
  lineage/figures/figure2.py
  lineage/figures/figure3.py
  lineage/figures/figure4.py
  lineage/figures/figure5.py
  lineage/figures/figure6.py
  makefile
Labels: bug, enhancement

#249 Vector viterbi
  lineage/Viterbi.py
  manuscript/00.front-matter.md
Labels: bug, enhancement, speed

#264 Lineage pruning REFACTOR
  lineage/Analyze.py
  lineage/BaumWelch.py
  lineage/CellVar.py
  lineage/DownwardRecursion.py
  lineage/LineageTree.py
  lineage/StateDistribution.py
  lineage/UpwardRecursion.py
  lineage/Viterbi.py
  lineage/figures/figure2.py
  lineage/figures/figure3.py
  lineage/figures/figure4.py
  lineage/figures/figure5.py
  lineage/figures/figure6.py
  lineage/figures/figure7.py
  lineage/figures/figureCommon.py
  lineage/tHMM.py
  lineage/tests/test_BaumWelch.py
  lineage/tests/test_CellVar.py
  lineage/tests/test_LineageTree.py
  lineage/tests/test_StateDistribution.py
  lineage/tests/test_tHMM.py
Labels: current, enhancement, speed
